# Generated by Django 5.2.8 on 2025-11-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("population", models.BigIntegerField(blank=True, null=True)),
                ("terrains", models.BigIntegerField(blank=True, null=True)),
                ("climates", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
