# Generated by Django 5.2.8 on 2025-12-01 04:05
from django.core.management import call_command
from django.db import migrations


def fill_planets(apps, schema_editor):
    call_command("fill_planets")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("planets", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fill_planets, reverse_code=migrations.RunPython.noop),
    ]
